#!/usr/bin/env python3
"""Render the product-definition convergence into opportunity.js — shown under
the map on the Future Opportunity view, where the capabilities it would deliver
already sit.
"""
import json, pathlib
ROOT = pathlib.Path(__file__).resolve().parent.parent
cm = json.loads((ROOT / "data" / "convergence-map.json").read_text(encoding="utf-8"))
pdefs = json.loads((ROOT / "data" / "product-definitions.json").read_text(encoding="utf-8"))
NAMES = {"joann": "Joann", "sly": "Sly", "henry": "Henry", "josh": "Josh", "lia": "Lia", "ola": "Ola"}

cards = []
for c in cm["productConvergence"]:
    who = "".join('<span class="op-who">' + NAMES[m["contributor"]] + "</span>" for m in c["members"])
    cards.append(
        '<article class="op-card' + ("" if c["strength"] == "converged" else " is-partial") + '">'
        '<div class="op-head"><span class="op-count">' + str(len(c["members"])) + ' of 6</span>'
        '<span class="op-strength">' + c["strength"] + "</span></div>"
        "<h4>" + c["theme"] + "</h4><p>" + c["whatConverged"] + "</p>"
        + ('<p class="op-diff"><strong>What differs.</strong> ' + c["whatDiffers"] + "</p>" if c.get("whatDiffers") else "")
        + '<p class="op-why">' + c["whyItMatters"] + "</p>"
        '<div class="op-drawn">' + who + "</div></article>")

def author(c):
    caps = "".join(
        '<li class="' + ("is-wedge" if cap["isWedge"] else "") + '"><strong>' + cap["name"] + "</strong>"
        + ('<span class="op-wedge">starts here</span>' if cap["isWedge"] else "")
        + "<p>" + cap["description"] + "</p></li>"
        for cap in c["capabilities"])
    rows = []
    if c["primaryUser"] and c["primaryUser"] != "Not stated.":
        rows.append(("Who it is for", c["primaryUser"]))
    if c["coreJob"] and c["coreJob"] != "Not stated.":
        rows.append(("The job", c["coreJob"]))
    if c.get("position"):
        rows.append(("What is distinctive", c["position"]))
    if c.get("outOfScope") and c["outOfScope"] != "Not stated.":
        rows.append(("Out of scope", c["outOfScope"]))
    return ('<article class="op-author' + (" is-missing" if c["status"] != "supplied" else "") + '">'
            '<div class="op-author-head"><h4>' + c["displayName"] + "</h4>"
            + ('<span class="op-flag">not supplied</span>' if c["status"] != "supplied" else "")
            + '<span class="op-src">' + c["source"] + "</span></div>"
            '<p class="op-one">' + c["oneSentence"] + "</p>"
            '<ul class="op-caps">' + caps + "</ul>"
            + "".join('<div class="op-row"><span>' + k + "</span><p>" + v + "</p></div>" for k, v in rows)
            + "</article>")

authors = "".join(author(c) for c in pdefs["contributors"])

html = ('<div class="op-wrap">'
 '<header class="op-hero"><span class="op-kicker">What we would build to get there</span>'
 "<h3>The product this opportunity rests on</h3>"
 "<p>The capabilities above are a hypothesis about what the system could become. This is what six people independently "
 "said the product should do &mdash; read against the loops, the overlap is much larger than the disagreement.</p></header>"
 '<div class="op-subnav" role="group" aria-label="Choose a product view">'
   '<button type="button" class="btn btn-primary" data-op-panel="converged" aria-pressed="true">Where we converged</button>'
   '<button type="button" class="btn" data-op-panel="authors" aria-pressed="false">Every definition, by author</button>'
 "</div>"
 '<div class="op-panel" data-op-body="converged">'
   '<div class="op-grid">' + "".join(cards) + "</div>"
 "</div>"
 '<div class="op-panel" data-op-body="authors" hidden>'
   '<p class="op-lead">' + pdefs["note"] + "</p>"
   '<div class="op-authors">' + authors + "</div>"
 "</div>"
 '<p class="op-fine">Each capability above is governed by a balancing loop the team found independently: permissioned '
 "identity by trust and consent, coordinated delivery by the value gap, net relationship value by programme economics. "
 "Select a capability to see which.</p></div>")

js = """/* GENERATED by scripts/build-opportunity.py. Do not edit directly. */
(function () {
  "use strict";
  var root = document.querySelector("#loyalty-map-v2");
  var grid = document.querySelector("#lm2-grid");
  var controls = root && root.querySelector(".viz-controls");
  if (!root || !grid || !controls) return;

  var panel = document.createElement("section");
  panel.id = "opportunity-view";
  panel.hidden = true;
  panel.innerHTML = __HTML__;
  var legend = root.querySelector(":scope > .lm2-legend");
  if (legend) root.insertBefore(panel, legend);
  else root.appendChild(panel);

  function sync() {
    var onFuture = grid.getAttribute("data-view") === "future";
    var mapShowing = !root.querySelector(":scope > .lm2-map-wrap").hidden;
    panel.hidden = !(onFuture && mapShowing);
  }
  new MutationObserver(sync).observe(grid, {attributes: true, attributeFilter: ["data-view"]});
  root.querySelectorAll("[data-map-view], [data-cv-view], [data-nv-view], [data-sh-view]").forEach(function (b) {
    b.addEventListener("click", function () { setTimeout(sync, 0); });
  });

  panel.querySelectorAll("[data-op-panel]").forEach(function (tab) {
    tab.addEventListener("click", function () {
      var name = tab.getAttribute("data-op-panel");
      panel.querySelectorAll("[data-op-panel]").forEach(function (t) {
        var active = t === tab;
        t.setAttribute("aria-pressed", String(active));
        t.classList.toggle("btn-primary", active);
      });
      panel.querySelectorAll("[data-op-body]").forEach(function (b) {
        b.hidden = b.getAttribute("data-op-body") !== name;
      });
    });
  });

  var future = controls.querySelector('[data-map-view="future"]');
  if (future) { future.hidden = false; controls.appendChild(future); }
  sync();
})();
"""
(ROOT / "opportunity.js").write_text(js.replace("__HTML__", json.dumps(html)), encoding="utf-8")
print(f"wrote opportunity.js — {len(cards)} product clusters")
